version: "3"
services:
  emulator:
    build:
      context: ./services/emulator
    ports:
      - "8085:8085"
    env_file:
      - .env
  operator:
    build:
      context: ./services/operator
    env_file:
      - .env
    tty: true
  pub:
    build:
      context: ./services/pub
    env_file:
      - .env
    tty: true
  sub:
    build:
      context: ./services/sub
    ports:
      - "8080:8080"
